###

GET http://localhost:1234/book

###

GET http://localhost:1234/searchByGenre/drama
###

GET http://localhost:1234/chico@buarque.com

###

POST http://localhost:1234/registerUser
content-type: application/json 

{
    "name": "chico",
    "password": "pass",
    "email": "chico@buarque.com",
    "address": [{
        "rua": "chico",
        "bairro": "maria",
        "cep": 1234567,
        "numero": 123
    }]
}

###


POST http://localhost:1234/product/registerBook
content-type: application/json 

{
    "bookName": "essa gente",
    "author": "buarque",
    "publisher": "cia das letras",
    "genre": "romance",
    "status": "disponivel"
}